export const zipHubAbi = [
  {
    type: "constructor",
    stateMutability: "payable",
    inputs: [],
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "operator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "handleTo",
    stateMutability: "view",
    inputs: [{ name: "handle", type: "string" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "addressToHandle",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "poolBal",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "pool", type: "bytes32" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenBal",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "id", type: "bytes32" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "debt",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [{ name: "handle", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "lookup",
    stateMutability: "view",
    inputs: [{ name: "handle", type: "string" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "pay",
    stateMutability: "payable",
    inputs: [
      { name: "to", type: "address" },
      { name: "handle", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "payable",
    inputs: [{ name: "pool", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "pool", type: "bytes32" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "swap",
    stateMutability: "payable",
    inputs: [
      { name: "fromId", type: "bytes32" },
      { name: "toId", type: "bytes32" },
      { name: "amountIn", type: "uint256" },
    ],
    outputs: [{ name: "amountOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "borrow",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cashOut",
    stateMutability: "payable",
    inputs: [{ name: "dest", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "stockTrade",
    stateMutability: "payable",
    inputs: [
      { name: "symbol", type: "bytes32" },
      { name: "amount", type: "uint256" },
      { name: "buying", type: "bool" },
    ],
    outputs: [],
  },
] as const;
